#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate
python /app/compose/wait_for_elasticsearch.py
python manage.py rebuild_index --noinput
exec uvicorn config.asgi:application --host 0.0.0.0 --reload --reload-include '*.html'
