# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(blank=True, default='/Users/jpalanca/devel/ojoalplato/ojoalplato/mediauncategorized.gif', null=True, upload_to='/Users/jpalanca/devel/ojoalplato/ojoalplato/media'),
        ),
    ]
