# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20160821_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(blank=True, default='/app/ojoalplato/mediauncategorized.gif', null=True, upload_to='/app/ojoalplato/media'),
        ),
    ]
