# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-12 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20160825_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(blank=True, default='/mediauncategorized.gif', null=True, upload_to='/media'),
        ),
    ]
