# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 11:29
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Elaboración')),
                ('ingredients', taggit_autosuggest.managers.TaggableManager(blank=True, help_text='Lista de ingredientes separados por comas.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Ingredientes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Dirección')),
                ('last_visit', models.DateField(blank=True, null=True, verbose_name='Fecha última visita')),
                ('price', models.CharField(blank=True, max_length=50, null=True, verbose_name='Precio sin vino')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=2062, verbose_name='Posición en el mapa')),
            ],
            options={
                'verbose_name': 'Restaurante',
                'verbose_name_plural': 'Restaurantes',
            },
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('kind', models.CharField(choices=[('white', 'Blanco'), ('red', 'Tinto'), ('rose', 'Rosado')], max_length=50, verbose_name='Tipo')),
                ('last_taste', models.DateField(blank=True, null=True, verbose_name='Fecha última cata')),
                ('price', models.CharField(blank=True, max_length=50, null=True, verbose_name='Precio medio')),
                ('opinion', models.TextField(blank=True, null=True, verbose_name='Opinión')),
            ],
            options={
                'verbose_name': 'Vino',
                'verbose_name_plural': 'Vinos',
            },
        ),
    ]
