# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 18:49
from __future__ import unicode_literals

from django.db import migrations
import likert_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Receta', 'verbose_name_plural': 'Recetas'},
        ),
        migrations.AddField(
            model_name='restaurant',
            name='estrellas',
            field=likert_field.models.LikertField(blank=True, null=True, verbose_name='Estrellas michelín'),
        ),
    ]
