# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 19:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20160825_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='estrellas',
            new_name='stars',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='freedays',
            field=models.CharField(blank=True, max_length=80, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Días libres'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, verbose_name='Teléfono'),
        ),
    ]
