# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 21:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20160825_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='freedays',
            field=models.CharField(blank=True, max_length=80, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Días libres'),
        ),
    ]
