# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20160825_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Web'),
        ),
    ]
