# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-28 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_restaurant_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='avg_price',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Precio medio'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu_price',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Precio de menú'),
        ),
    ]
