# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-30 19:37
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_auto_20160828_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, max_length=200, null=True, populate_from='name', verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, max_length=200, null=True, populate_from='name', verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='wine',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, max_length=200, null=True, populate_from='name', verbose_name='slug'),
        ),
    ]
