# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-21 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_auto_20160830_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_header',
            field=models.ImageField(blank=True, help_text='Imagen', null=True, upload_to='/app/ojoalplato/media', verbose_name='Imagen de cabecera'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image_header',
            field=models.ImageField(blank=True, help_text='Imagen', null=True, upload_to='/app/ojoalplato/media', verbose_name='Imagen de cabecera'),
        ),
        migrations.AddField(
            model_name='wine',
            name='image_header',
            field=models.ImageField(blank=True, help_text='Imagen', null=True, upload_to='/app/ojoalplato/media', verbose_name='Imagen de cabecera'),
        ),
    ]
