# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-01 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_auto_20170521_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='chef',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cocinero'),
        ),
    ]
