# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-04 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import likert_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_restaurant_chef'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='awards',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Distinciones'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='suns',
            field=likert_field.models.LikertField(blank=True, null=True, verbose_name='Soles Repsol'),
        ),
    ]
