# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-08 03:30
from __future__ import unicode_literals

from django.db import migrations
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('cards', '0015_auto_20170606_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='tags',
            field=taggit_autosuggest.managers.TaggableManager(blank=True, help_text='Lista de etiquetas separadas por comas.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Etiquetas'),
        ),
    ]
