# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-10 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0018_auto_20170826_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='avg_price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Precio medio'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu_price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Precio de menú'),
        ),
    ]
