# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-10 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0019_auto_20170910_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='manager',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Jefe/a de Sala'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='sumiller',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sumiller'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='chef',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cocinero/a'),
        ),
    ]
