# Generated by Django 3.1.6 on 2021-02-09 17:52

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0020_auto_20171210_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_header',
            field=models.ImageField(blank=True, help_text='Imagen', null=True, upload_to='.', verbose_name='Imagen de cabecera'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='freedays',
            field=models.CharField(blank=True, max_length=80, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Días cerrado'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image_header',
            field=models.ImageField(blank=True, help_text='Imagen', null=True, upload_to='.', verbose_name='Imagen de cabecera'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='image_header',
            field=models.ImageField(blank=True, help_text='Imagen', null=True, upload_to='.', verbose_name='Imagen de cabecera'),
        ),
    ]
