# Generated by Django 3.2.13 on 2022-08-28 18:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hitcount.models
import model_utils.fields
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('cards', '0021_auto_20210209_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='VarietyTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Variedad',
                'verbose_name_plural': 'Variedades',
            },
        ),
        migrations.CreateModel(
            name='Winery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre de Bodega')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Web')),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'ordering': ['name'],
            },
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
        migrations.AddField(
            model_name='wine',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='wine',
            name='other',
            field=models.TextField(blank=True, null=True, verbose_name='Otros datos'),
        ),
        migrations.AddField(
            model_name='wine',
            name='preparation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Elaboración'),
        ),
        migrations.AddField(
            model_name='wine',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='kind',
            field=models.CharField(choices=[('white', 'Blanco'), ('red', 'Tinto'), ('rose', 'Rosado'), ('sparkling', 'Espumoso'), ('sweet', 'Dulce')], max_length=50, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='TaggedVariety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_taggedvariety_items', to='cards.varietytag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaggedRestaurantTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.restaurant')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_taggedrestauranttag_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='wine',
            name='variety',
            field=taggit_autosuggest.managers.TaggableManager(blank=True, help_text='Lista de variedades de uva separadas por comas.', through='cards.TaggedVariety', to='cards.VarietyTag', verbose_name='Variedades'),
        ),
        migrations.AddField(
            model_name='wine',
            name='winery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.winery', verbose_name='Bodega'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='tags',
            field=taggit_autosuggest.managers.TaggableManager(blank=True, help_text='Lista de etiquetas separadas por comas.', through='cards.TaggedRestaurantTag', to='taggit.Tag', verbose_name='Etiquetas'),
        ),
    ]
