# Generated by Django 3.2.13 on 2022-08-28 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0022_auto_20220828_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='taggedvariety',
            name='content_object',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cards.wine'),
            preserve_default=False,
        ),
    ]
