# Generated by Django 3.2.13 on 2022-08-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0024_rename_variety_wine_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='image_label',
            field=models.ImageField(blank=True, help_text='Imagen de etiqueta', null=True, upload_to='.', verbose_name='Imagen de etiqueta'),
        ),
    ]
