# Generated by Django 3.2.13 on 2022-08-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0025_wine_image_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='image_label',
        ),
        migrations.AddField(
            model_name='wine',
            name='image_bottle',
            field=models.ImageField(blank=True, help_text='Imagen de la botella', null=True, upload_to='.', verbose_name='Imagen de la botella'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='image_header',
            field=models.ImageField(blank=True, help_text='Imagen de la etiqueta', null=True, upload_to='.', verbose_name='Imagen de la etiqueta'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='kind',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo'),
        ),
    ]
