# Generated by Django 3.2.13 on 2022-08-29 13:55

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0026_auto_20220829_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='kind',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Blanco'), (2, 'Tinto'), (3, 'Rosado'), (4, 'Espumoso'), (5, 'Dulce')], max_length=10, null=True, verbose_name='Tipo'),
        ),
    ]
