# Generated by Django 3.2.13 on 2022-08-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0027_alter_wine_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='parker_points',
            field=models.IntegerField(blank=True, null=True, verbose_name='Puntos Parker'),
        ),
        migrations.AddField(
            model_name='wine',
            name='penyin_points',
            field=models.IntegerField(blank=True, null=True, verbose_name='Puntos Peñin'),
        ),
    ]
