# Generated by Django 3.2.13 on 2022-08-29 15:49

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0028_auto_20220829_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='cata_color_blanco',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Amarillo Verdoso'), (1, 'Amarillo Paja'), (2, 'Limón'), (3, 'Dorado'), (4, 'Ámbar'), (5, 'Castaño')], max_length=10, null=True, verbose_name='Tonalidades del Color (Blanco)'),
        ),
        migrations.AddField(
            model_name='wine',
            name='cata_color_rosado',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Fresa'), (1, 'Salmón'), (2, 'Anaranjado')], max_length=10, null=True, verbose_name='Tonalidades del Color (Rosado)'),
        ),
        migrations.AddField(
            model_name='wine',
            name='cata_color_tinto',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Rojo Rubí'), (1, 'Rojo Granate'), (2, 'Rojo Violeta'), (3, 'Rojo Pardo'), (4, 'Rojo Teja')], max_length=10, null=True, verbose_name='Tonalidades del Color (Tinto)'),
        ),
        migrations.AddField(
            model_name='wine',
            name='cata_efervescencia',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Tranquilo'), (1, 'Aguja'), (2, 'Burbujas finas'), (3, 'Burbujas grandes'), (4, 'Rosarios escasos'), (5, 'Rosarios medios'), (6, 'Rosarios abundantes'), (7, 'Corona'), (8, 'Sin corona')], max_length=10, null=True, verbose_name='Efervescencia'),
        ),
        migrations.AddField(
            model_name='wine',
            name='cata_fluidez',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Muy fluido'), (1, 'Fluido'), (2, 'Untuoso'), (3, 'Graso'), (4, 'Viscoso')], max_length=10, null=True, verbose_name='Fluidez'),
        ),
        migrations.AddField(
            model_name='wine',
            name='cata_gust_acidez',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Escasa'), (1, 'Apreciable'), (2, 'Equilibrada'), (3, 'Acídulo'), (4, 'Excesiva')], max_length=10, null=True, verbose_name='Acidez'),
        ),
        migrations.AddField(
            model_name='wine',
            name='cata_gust_alcohol',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Liviano'), (1, 'Suficiente'), (2, 'Medio'), (3, 'Cálido'), (4, 'Espirituoso')], max_length=10, null=True, verbose_name='Alcohol'),
        ),
        migrations.AddField(
            model_name='wine',
            name='cata_gust_ataque',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Malo'), (1, 'Ordinario'), (2, 'Placentero'), (3, 'Muy agradable')], max_length=10, null=True, verbose_name='Ataque'),
        ),
        migrations.AddField(
            model_name='wine',
            name='cata_gust_boca',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Desecado'), (1, 'Fluyente'), (2, 'Aterciopelado'), (3, 'Untuoso')], max_length=10, null=True, verbose_name='Paso en boca'),
        ),
        migrations.AddField(
            model_name='wine',
            name='cata_gust_cuerpo',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Flaco'), (1, 'Delgado'), (2, 'Lleno'), (3, 'Redondo'), (4, 'Graso'), (5, 'Corpulento')], max_length=10, null=True, verbose_name='Cuerpo'),
        ),
        migrations.AddField(
            model_name='wine',
            name='cata_gust_dulzor',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Brut'), (1, 'Seco'), (2, 'Dulce'), (3, 'Azucarado')], max_length=10, null=True, verbose_name='Dulzor'),
        ),
        migrations.AddField(
            model_name='wine',
            name='cata_gust_persistencia',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Poco persistente'), (1, 'Moderado'), (2, 'Bastante'), (3, 'Muy persistente')], max_length=10, null=True, verbose_name='Persistencia'),
        ),
        migrations.AddField(
            model_name='wine',
            name='cata_gust_tanino',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Blando'), (1, 'Poco tánico'), (2, 'Equilibrado'), (3, 'Astringente'), (4, 'Áspero'), (5, 'Amargo')], max_length=10, null=True, verbose_name='Tanino'),
        ),
        migrations.AddField(
            model_name='wine',
            name='cata_intensidad',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Despojado'), (1, 'Pálido'), (2, 'Ligero'), (3, 'Medio'), (4, 'Intenso'), (5, 'Profundo')], max_length=10, null=True, verbose_name='Intensidad'),
        ),
        migrations.AddField(
            model_name='wine',
            name='cata_limpidez',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Cristalino'), (1, 'Turbio')], max_length=10, null=True, verbose_name='Limpidez'),
        ),
        migrations.AddField(
            model_name='wine',
            name='cata_olf_1a',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Desagradable'), (1, 'Ordinaria'), (2, 'Agradable')], max_length=10, null=True, verbose_name='1ª Impresión'),
        ),
        migrations.AddField(
            model_name='wine',
            name='cata_olf_aroma_1',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Afrutados'), (1, 'Florales'), (2, 'Vegetales'), (3, 'Especias'), (4, 'Mineral')], max_length=10, null=True, verbose_name='Aroma (Carácter) Primarios (cepa)'),
        ),
        migrations.AddField(
            model_name='wine',
            name='cata_olf_aroma_2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Alcoholes'), (1, 'Lácticos'), (2, 'Ácidos'), (3, 'Levadura'), (4, 'Azufroso')], max_length=10, null=True, verbose_name='Aroma (Carácter) Secundarios (fermentación)'),
        ),
        migrations.AddField(
            model_name='wine',
            name='cata_olf_aroma_3',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Madera'), (1, 'Tabaco'), (2, 'Frutos secos'), (3, 'Cuero'), (4, 'Acético'), (5, 'Mohoso'), (6, 'Corcho')], max_length=10, null=True, verbose_name='Aroma (Carácter) Terciarios (Maduración)'),
        ),
        migrations.AddField(
            model_name='wine',
            name='cata_olf_intensidad',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Inexistente'), (1, 'Débil'), (2, 'Medio'), (3, 'Intenso'), (4, 'Potente')], max_length=10, null=True, verbose_name='Intensidad'),
        ),
    ]
