# Generated by Django 3.2.13 on 2022-08-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0030_auto_20220829_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='show_tasting_form',
            field=models.BooleanField(default=False, verbose_name='Mostrar Ficha de cata'),
        ),
    ]
