# Generated by Django 3.2.13 on 2022-08-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0031_wine_show_tasting_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='preparation',
            field=models.TextField(blank=True, null=True, verbose_name='Elaboración'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Añada'),
        ),
    ]
