# Generated by Django 3.2.13 on 2022-08-31 17:16

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0033_auto_20220831_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='cata_gust_valoracion',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Aterciopelado'), (1, 'Equilibrado'), (2, 'Elegante'), (3, 'Redondo'), (4, 'Estructurado'), (5, 'Suave'), (6, 'Ligero'), (7, 'Denso')], max_length=20, null=True, verbose_name='Valoración'),
        ),
    ]
