# Generated by Django 3.2.13 on 2022-09-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0035_auto_20220902_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='image_back',
            field=models.ImageField(blank=True, help_text='Imagen de la etiqueta trasera', null=True, upload_to='.', verbose_name='Imagen de la etiqueta trasera'),
        ),
    ]
