# Generated by Django 3.2.13 on 2023-01-21 10:51

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0036_wine_image_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='cata_gust_ataque',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Malo'), (1, 'Ordinario'), (4, 'Bueno'), (2, 'Placentero'), (5, 'Goloso'), (3, 'Muy agradable')], max_length=20, null=True, verbose_name='Ataque'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='cata_gust_persistencia',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(3, 'Intensa'), (0, 'Alta'), (4, 'Larga'), (1, 'Media'), (2, 'Baja')], max_length=20, null=True, verbose_name='Persistencia'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='cata_gust_sensacion',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Acidez buena'), (1, 'Acidez marcada'), (11, 'Sensación salina'), (2, 'Amargor ligero'), (12, 'Ácido'), (8, 'Astringente'), (13, 'Cálido'), (10, 'Acuoso'), (14, 'Fresco'), (15, 'Denso')], max_length=40, null=True, verbose_name='Sensacion'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='cata_olf_aroma',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Florales'), (1, 'Flor blanca'), (2, 'Clavel'), (3, 'Violeta'), (4, 'Rosa'), (5, 'Afrutados'), (6, 'Manzana'), (7, 'Pera'), (8, 'Melocotón'), (9, 'Albaricoque'), (10, 'Cítricos'), (11, 'Frutas tropicales'), (12, 'Cereza'), (13, 'Frutos rojos'), (14, 'Frutos negros'), (15, 'Membrillo'), (49, 'Golosinas'), (16, 'Vegetales'), (17, 'Hinojo'), (18, 'Pimiento verde'), (19, 'Trufa'), (20, 'Hojarasca'), (50, 'Hierbas aromáticas'), (21, 'Especias'), (22, 'Pimienta'), (23, 'Canela'), (24, 'Clavo'), (25, 'Coco'), (26, 'Mineral'), (27, 'Tiza'), (28, 'Yeso'), (29, 'Grafito'), (30, 'Yodo'), (31, 'Pedernal'), (32, 'Sílice'), (33, 'Lácticos'), (34, 'Mantequilla'), (35, 'Yogur'), (36, 'Levadura'), (37, 'Miga de pan'), (38, 'Azufroso'), (39, 'Barniz'), (40, 'Laca de uñas'), (41, 'Caramelo'), (42, 'Madera'), (43, 'Tabaco'), (44, 'Frutos secos'), (45, 'Cuero'), (51, 'Balsámicos'), (46, 'Vainilla'), (47, 'Café'), (53, 'Cacao'), (48, 'Tostados'), (52, 'Manzana compotada')], max_length=200, null=True, verbose_name='Aroma'),
        ),
    ]
