# Generated by Django 3.2.13 on 2023-06-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0036_wine_image_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='guide_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Guía'),
        ),
    ]
