# Generated by Django 3.2.13 on 2023-01-21 11:26

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0037_auto_20230121_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='cata_gust_sensacion',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Acidez buena'), (1, 'Acidez marcada'), (6, 'Sensación salina'), (2, 'Amargor varietal suave'), (3, 'Amargor varietal marcado'), (4, 'Dulzor ligero'), (5, 'Dulzor marcado'), (12, 'Ácido'), (7, 'Astringencia suave'), (8, 'Astringencia marcada'), (13, 'Cálido'), (10, 'Acuoso'), (14, 'Fresco'), (15, 'Denso')], max_length=40, null=True, verbose_name='Sensacion'),
        ),
    ]
