# Generated by Django 3.2.13 on 2023-06-04 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0037_restaurant_guide_notes'),
        ('cards', '0039_alter_wine_cata_color_blanco'),
    ]

    operations = [
    ]
