# Generated by Django 3.2.13 on 2024-08-04 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0040_merge_20230604_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='winery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wines', to='cards.winery', verbose_name='Bodega'),
        ),
    ]
