# Generated by Django 3.2.13 on 2024-08-04 11:32

from django.db import migrations, models
import django.db.models.deletion
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0041_alter_wine_winery'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaggedClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_taggedclass_items', to='cards.classtag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='wine',
            name='classes',
            field=taggit_autosuggest.managers.TaggableManager(blank=True, help_text='Asegúrate de usar clases específicas.', through='cards.TaggedClass', to='cards.ClassTag', verbose_name='Clase'),
        ),
    ]
