# Generated by Django 3.2.13 on 2024-08-04 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0042_auto_20240804_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='taggedclass',
            name='content_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.wine'),
        ),
    ]
