# Generated by Django 3.2.13 on 2024-08-04 14:08

from django.db import migrations
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0043_taggedclass_content_object'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classtag',
            options={'verbose_name': 'Clase', 'verbose_name_plural': 'Clases'},
        ),
        migrations.AlterField(
            model_name='wine',
            name='classes',
            field=taggit_autosuggest.managers.TaggableManager(blank=True, help_text='Lista de clases de envejecimiento, separadas por comas.', through='cards.TaggedClass', to='cards.ClassTag', verbose_name='Clase'),
        ),
    ]
