# Generated by Django 3.2.13 on 2023-06-18 10:45

import autoslug.fields
from django.db import migrations, models
import django.utils.timezone
import hitcount.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0040_merge_20230604_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=200, populate_from='title', verbose_name='slug')),
                ('introduction', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, help_text='Imagen', upload_to='guides', verbose_name='Imagen de portada')),
                ('restaurants', models.ManyToManyField(related_name='guides', to='cards.Restaurant')),
            ],
            options={
                'ordering': ('-created',),
            },
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
    ]
