# Generated by Django 3.2.13 on 2023-06-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0040_merge_20230604_1822'),
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guide',
            options={'ordering': ('-created',), 'verbose_name': 'Guía', 'verbose_name_plural': 'Guías'},
        ),
        migrations.AlterField(
            model_name='guide',
            name='city',
            field=models.CharField(max_length=255, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='introduction',
            field=models.TextField(blank=True, verbose_name='Introducción'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='restaurants',
            field=models.ManyToManyField(related_name='guides', to='cards.Restaurant', verbose_name='Restaurantes'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
    ]
