# Generated by Django 3.2.13 on 2023-07-30 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210209_1852'),
        ('users', '0004_auto_20220828_1326'),
    ]

    operations = [
    ]
