# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160805_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmeta',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='blog.Post'),
        ),
    ]
