# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160806_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_filtered',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='password',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='ping_status',
            field=models.CharField(blank=True, choices=[('closed', 'closed'), ('open', 'open')], max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='pinged',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='to_ping',
            field=models.TextField(blank=True),
        ),
    ]
