# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20160806_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmeta',
            name='value',
            field=models.TextField(blank=True),
        ),
    ]
