# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-21 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20160821_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'borrador'), ('publish', 'publicado')], max_length=20, verbose_name='Estado'),
        ),
    ]
