# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20160822_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'post_date', 'ordering': ['-post_date'], 'verbose_name': 'Artículo', 'verbose_name_plural': 'Artículos'},
        ),
    ]
