# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20160823_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='post',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='published_at',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', when=set(['publish'])),
        ),
        migrations.AlterField(
            model_name='post',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
