# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-29 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20160825_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='recipe_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='cards.Recipe', verbose_name='Ficha de receta'),
        ),
        migrations.AlterField(
            model_name='post',
            name='restaurant_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='cards.Restaurant', verbose_name='Ficha de restaurante'),
        ),
        migrations.AlterField(
            model_name='post',
            name='wine_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='cards.Wine', verbose_name='Ficha de vino'),
        ),
    ]
