# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-30 19:37
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20160829_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_header',
            field=models.ImageField(blank=True, help_text='Imagen de 850px x 398px', null=True, upload_to='/app/ojoalplato/media', verbose_name='Imagen de cabecera'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=200, populate_from='title', verbose_name='Slug'),
        ),
    ]
