# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-30 10:23
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20160830_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='Fecha publicación', when=set(['publish'])),
        ),
    ]
