# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-12 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20170512_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('attachment', 'attachment'), ('page', 'page'), ('post', 'post'), ('revision', 'revision')], default='post', max_length=20),
        ),
    ]
