# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-12 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20170512_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha publicación'),
        ),
    ]
