# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-14 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20170512_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='notified',
            field=models.BooleanField(default=False, verbose_name='Notificación enviada'),
        ),
    ]
