# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-17 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_post_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='notification_delay',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Retardo de notificación (horas)'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_to_facebook',
            field=models.BooleanField(default=True, verbose_name='Publicar en Facebook'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_to_twitter',
            field=models.BooleanField(default=True, verbose_name='Publicar en Twitter'),
        ),
    ]
