# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-09 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20170517_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='restaurant_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='cards.Restaurant', verbose_name='Ficha de restaurante'),
        ),
    ]
