# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-07 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20170517_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Subtítulo'),
        ),
    ]
