# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-26 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_post_subtitle'),
        ('blog', '0031_auto_20170809_0447'),
    ]

    operations = [
    ]
