# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-19 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_to_facebook',
            field=models.BooleanField(default=False, verbose_name='Publicar en Facebook'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_to_twitter',
            field=models.BooleanField(default=False, verbose_name='Publicar en Twitter'),
        ),
    ]
