# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-09 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20170919_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='menu_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='parent_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, choices=[('attachment', 'attachment'), ('page', 'page'), ('post', 'post'), ('revision', 'revision')], default='post', max_length=20, null=True),
        ),
    ]
