# Generated by Django 3.1.6 on 2021-02-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20171210_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_header',
            field=models.ImageField(blank=True, help_text='Imagen de 850px x 398px', null=True, upload_to='.', verbose_name='Imagen de cabecera'),
        ),
    ]
